# Generated by Django 5.1.6 on 2025-02-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email_address',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
